workspace:
  base: /drone
  path: src

branches: [master, stable10, stable9.1, stable9]

clone:
  git:
    image: plugins/git
    depth: 50

pipeline:
  restore:
    image: plugins/s3-cache:1
    pull: true
    secrets: [ cache_s3_endpoint, cache_s3_access_key, cache_s3_secret_key ]
    restore: true
    when:
      local: false
      event: [push, pull_request]

  composer:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - ./tests/drone/composer-install.sh
    when:
      event: [push, pull_request]

  yarn:
    image: owncloudci/nodejs:latest
    pull: true
    commands:
      - ./tests/drone/yarn-install.sh
    when:
      event: [push, pull_request]

  rebuild:
    image: plugins/s3-cache:1
    pull: true
    secrets: [ cache_s3_endpoint, cache_s3_access_key, cache_s3_secret_key ]
    rebuild: true
    mount:
      - lib/composer
      - core/vendor
      - build/node_modules
    when:
      local: false
      event: [ push ]
      matrix:
        TEST_SUITE: javascript

  flush:
    image: plugins/s3-cache:1
    pull: true
    secrets: [ cache_s3_endpoint, cache_s3_access_key, cache_s3_secret_key ]
    flush: true
    flush_age: 14
    when:
      local: false
      event: [push]
      matrix:
        TEST_SUITE: javascript

  owncloud-coding-standard:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - make test-php-style
    when:
      matrix:
        TEST_SUITE: owncloud-coding-standard

  php-phan-71:
    image: owncloudci/php:7.1
    pull: true
    commands:
      - make test-php-phan
    when:
      matrix:
        TEST_SUITE: phan

  php-phan-72:
    image: owncloudci/php:7.2
    pull: true
    commands:
      - make test-php-phan
    when:
      matrix:
        TEST_SUITE: phan

  php-phan-73:
    image: owncloudci/php:7.3
    pull: true
    commands:
      - make test-php-phan
    when:
      matrix:
        TEST_SUITE: phan

  install-server:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - ./tests/drone/install-server.sh
      - php occ a:l
      - php occ config:system:set trusted_domains 1 --value=server
      - php occ config:system:set trusted_domains 2 --value=federated
      - php occ log:manage --level 0
      - php occ config:list
    when:
      matrix:
        INSTALL_SERVER: true

  install-testing-app:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - git clone https://github.com/owncloud/testing.git $$DRONE_WORKSPACE/apps/testing
      - php occ a:l
      - php occ a:e testing
      - php occ a:l
    when:
      matrix:
        INSTALL_TESTING_APP: true

  federated:
    image: toolhippie/docker:latest
    pull: true
    detach: true
    environment:
      - DOCKER_HOST=tcp://docker:2375
    commands:
      - |
        docker run -p 8000:8080 \
        -e DEBUG=true \
        -e OWNCLOUD_APPS_INSTALL=https://github.com/owncloud/testing/releases/download/latest/testing.tar.gz \
        -e OWNCLOUD_APPS_ENABLE=testing \
        owncloud/server:latest
    when:
      matrix:
        TEST_FEDERATION: true

  wait-for-federated-server:
    image: owncloud/ubuntu:latest
    pull: true
    commands:
      - wait-for-it -t 600 docker:8000
    when:
      matrix:
        TEST_FEDERATION: true

  prepare-objectstore:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - cd /drone/src/apps
      - git clone https://github.com/owncloud/files_primary_s3.git
      - cd files_primary_s3
      - composer install
      - cp tests/drone/scality.config.php /drone/src/config
      - cd /drone/src
      - php occ a:l
      - php occ a:e files_primary_s3
      - php occ a:l
      - php ./occ s3:create-bucket owncloud --accept-warning
    when:
      matrix:
        TEST_OBJECTSTORAGE: true

  phpstan:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - make test-php-phpstan
    when:
      matrix:
        TEST_SUITE: phpstan

  phpunit:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    group: test
    environment:
      - PHP_VERSION=${PHP_VERSION}
      - DB_TYPE=${DB_TYPE}
      - FILES_EXTERNAL_TYPE=${FILES_EXTERNAL_TYPE}
      - COVERAGE=${COVERAGE}
    commands:
      - ./tests/drone/test-phpunit.sh
    when:
      matrix:
        TEST_SUITE: phpunit

  test-javascript:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - ./tests/drone/test-javascript.sh
    when:
      matrix:
        TEST_SUITE: javascript

  codecov:
    image: plugins/codecov:2
    secrets: [codecov_token]
    pull: true
    flags:
     - ${TEST_SUITE}
    files:
     - '*.xml'
    paths:
     - tests/output/coverage
    when:
      event: [push, pull_request]
      matrix:
        COVERAGE: true

  setup-caldav-carddav-tests:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - bash apps/dav/tests/ci/${TEST_SUITE}/install.sh
    when:
      matrix:
        CALDAV_CARDDAV_JOB: true

  install-notifications-app:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - git clone https://github.com/owncloud/notifications.git apps/notifications
      - php occ a:e notifications
    when:
      matrix:
        INSTALL_NOTIFICATIONS_APP: true

  fix-permissions:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - chown www-data /drone/src -R
    when:
      matrix:
        CHOWN_SERVER: true

  litmus-setup:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - echo "Create local mount ...."
      - mkdir -p /drone/src/work/local_storage
      - php occ app:enable files_external
      - php occ config:system:set files_external_allow_create_new_local --value=true
      - php occ config:app:set core enable_external_storage --value=yes
      - php occ files_external:create local_storage local null::null -c datadir=/drone/src/work/local_storage
      - echo 'Sharing a folder ..'
      - OC_PASS=123456 php occ user:add --password-from-env user1
      - chown www-data /drone/src -R
      - curl -k -s -u user1:123456 -X MKCOL 'http://server/remote.php/webdav/new_folder'
      - curl -k -s -u user1:123456 "http://server/ocs/v2.php/apps/files_sharing/api/v1/shares" --data 'path=/new_folder&shareType=0&permissions=15&name=new_folder&shareWith=admin'
    when:
      matrix:
        TEST_SUITE: litmus

  litmus-old-endpoint:
    image: owncloud/litmus
    pull: true
    environment:
      - LITMUS_URL=http://server/remote.php/webdav
      - LITMUS_USERNAME=admin
      - LITMUS_PASSWORD=admin
    when:
      matrix:
        TEST_SUITE: litmus

  litmus-new-endpoint:
    image: owncloud/litmus
    pull: true
    environment:
    - LITMUS_URL=http://server/remote.php/dav/files/admin
    - LITMUS_USERNAME=admin
    - LITMUS_PASSWORD=admin
    when:
      matrix:
        TEST_SUITE: litmus

  litmus-new-endpoint-mount:
    image: owncloud/litmus
    pull: true
    environment:
    - LITMUS_URL=http://server/remote.php/dav/files/admin/local_storage/
    - LITMUS_USERNAME=admin
    - LITMUS_PASSWORD=admin
    when:
      matrix:
        TEST_SUITE: litmus

  litmus-old-endpoint-mount:
    image: owncloud/litmus
    pull: true
    environment:
    - LITMUS_URL=http://server/remote.php/webdav/local_storage/
    - LITMUS_USERNAME=admin
    - LITMUS_PASSWORD=admin
    when:
      matrix:
        TEST_SUITE: litmus

  litmus-new-endpoint-shared:
    image: owncloud/litmus
    pull: true
    environment:
    - LITMUS_URL=http://server/remote.php/dav/files/admin/new_folder/
    - LITMUS_USERNAME=admin
    - LITMUS_PASSWORD=admin
    when:
      matrix:
        TEST_SUITE: litmus

  litmus-old-endpoint-shared:
    image: owncloud/litmus
    pull: true
    environment:
    - LITMUS_URL=http://server/remote.php/webdav/new_folder/
    - LITMUS_USERNAME=admin
    - LITMUS_PASSWORD=admin
    when:
      matrix:
        TEST_SUITE: litmus

  owncloud-log:
    image: owncloud/ubuntu:16.04
    detach: true
    pull: true
    commands:
      - tail -f /drone/src/data/owncloud.log
    when:
      status: [ success, failure ]
      matrix:
        OWNCLOUD_LOG: true

  api-acceptance-tests:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - TEST_SERVER_URL=http://server
      - TEST_FEDERATION=${TEST_FEDERATION}
    commands:
      - if [ "${TEST_FEDERATION}" != "" ]; then export TEST_SERVER_FED_URL="http://docker:8000"; fi
      - make test-acceptance-api TESTING_REMOTE_SYSTEM=true
    when:
      matrix:
        TEST_SUITE: api

  cli-acceptance-tests:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - TEST_SERVER_URL=http://server
      - MAILHOG_HOST=email
    commands:
      - touch /drone/saved-settings.sh
      - . /drone/saved-settings.sh
      - make test-acceptance-cli TESTING_REMOTE_SYSTEM=true
    when:
      matrix:
        TEST_SUITE: cli

  webui-acceptance-tests:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - BROWSER=chrome
      - SELENIUM_HOST=selenium
      - SELENIUM_PORT=4444
      - TEST_SERVER_URL=http://server
      - PLATFORM=Linux
      - MAILHOG_HOST=email
      - TEST_FEDERATION=${TEST_FEDERATION}
    commands:
      - if [ "${TEST_FEDERATION}" != "" ]; then export TEST_SERVER_FED_URL="http://docker:8000"; fi
      - make test-acceptance-webui TESTING_REMOTE_SYSTEM=true
    when:
      matrix:
        TEST_SUITE: selenium

  caldav-carddav-tests:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - bash apps/dav/tests/ci/${TEST_SUITE}/script.sh
    when:
      matrix:
        CALDAV_CARDDAV_JOB: true

  print-log:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - cat /drone/src/data/owncloud.log
    when:
      status:  [ failure ]
      matrix:
        TEST_SUITE: phpunit

  notify:
    image: plugins/slack:1
    pull: true
    secrets:
      - source: slack_webhook_public
        target: slack_webhook
    channel: server
    when:
      status: [ failure, changed ]
      event: [ push, tag ]

services:
  mariadb:
    image: ${MARIADB_IMAGE=mariadb:10.2}
    environment:
      - MYSQL_USER=owncloud
      - MYSQL_PASSWORD=owncloud
      - MYSQL_DATABASE=owncloud
      - MYSQL_ROOT_PASSWORD=owncloud
    when:
      matrix:
        DB_TYPE: mariadb

  mysql:
    image: ${MYSQL_IMAGE=mysql:5.5}
    environment:
      - MYSQL_USER=owncloud
      - MYSQL_PASSWORD=owncloud
      - MYSQL_DATABASE=owncloud
      - MYSQL_ROOT_PASSWORD=owncloud
    when:
      matrix:
        DB_TYPE: mysql

  mysql8:
    image: ${MYSQL_IMAGE=mysql:8.0}
    # see http://php.net/manual/en/mysqli.requirements.php
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_USER=owncloud
      - MYSQL_PASSWORD=owncloud
      - MYSQL_DATABASE=owncloud
      - MYSQL_ROOT_PASSWORD=owncloud
    when:
      matrix:
        DB_TYPE: mysql8

  postgres:
    image: ${POSTGRES_IMAGE=postgres:9.4}
    environment:
      - POSTGRES_USER=owncloud
      - POSTGRES_PASSWORD=owncloud
      - POSTGRES_DB=owncloud
    when:
      matrix:
        DB_TYPE: postgres

  oracle:
    image: deepdiver/docker-oracle-xe-11g:2.0
    environment:
      - ORACLE_DISABLE_ASYNCH_IO=true
    when:
      matrix:
        DB_TYPE: oracle

  selenium:
    image: selenium/standalone-chrome-debug:latest
    pull: true
    when:
      matrix:
        TEST_SUITE: selenium

  server:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - APACHE_WEBROOT=/drone/src/
    command: [ "/usr/local/bin/apachectl", "-e", "debug" , "-D", "FOREGROUND" ]
    when:
      matrix:
        USE_SERVER: true

  docker:
    image: docker:18.04-dind
    when:
      matrix:
        TEST_FEDERATION: true

  apache_webdav:
    image: owncloudci/php
    pull: true
    environment:
     - APACHE_CONFIG_TEMPLATE=webdav
    command: [ "apachectl", "-D", "FOREGROUND" ]
    when:
      matrix:
        FILES_EXTERNAL_TYPE: webdav_apache

  smb_samba:
    image: owncloudci/samba
    pull: true
    command: "-u \"test;test\" -s \"public;/tmp;yes;no;no;test;none;test\" -S"
    when:
      matrix:
        FILES_EXTERNAL_TYPE: smb_samba

  ceph:
    image: owncloudci/ceph
    pull: true
    environment:
      - KEYSTONE_PUBLIC_PORT=5034
      - KEYSTONE_ADMIN_USER=test
      - KEYSTONE_ADMIN_PASS=testing
      - KEYSTONE_ADMIN_TENANT=testtenant
      - KEYSTONE_ENDPOINT_REGION=testregion
      - KEYSTONE_SERVICE=testceph
      - OSD_SIZE=500
    when:
      matrix:
        FILES_EXTERNAL_TYPE: swift

  scality:
    image: owncloudci/scality-s3server
    pull: true
    environment:
      - HOST_NAME=scality
    when:
      matrix:
        TEST_OBJECTSTORAGE: true

  email:
    image: mailhog/mailhog
    pull: true
    when:
      matrix:
        USE_EMAIL: true
matrix:
  include:

  # API Acceptance tests

    - PHP_VERSION: 7.1
      TEST_SUITE: api
      BEHAT_SUITE: apiFederation
      DB_TYPE: mariadb
      USE_SERVER: true
      TEST_FEDERATION: true
      INSTALL_SERVER: true
      CHOWN_SERVER: true
      OWNCLOUD_LOG: true
      INSTALL_TESTING_APP: true

 
    - PHP_VERSION: 7.1
      TEST_SUITE: selenium
      BEHAT_SUITE: webUISharingNotifications
      DB_TYPE: mariadb
      USE_SERVER: true
      TEST_FEDERATION: true
      INSTALL_SERVER: true
      CHOWN_SERVER: true
      OWNCLOUD_LOG: true
      INSTALL_TESTING_APP: true
      USE_EMAIL: true
      INSTALL_NOTIFICATIONS_APP: true
