<?php script('notificationsmail', 'notification_options'); ?>
<div id="email_notifications" class="section">
	<h2 class="app-name"><?php p($l->t('Notifications Email'));?></h2>
	<?php if($_['validUserObject']): ?>
	<p><?php p($l->t('You can receive notifications generated by any app in your configured email address. Choose if you let %s to send you such emails.', [$theme->getName()])); ?></p>
	<select id="email_sending_option">
		<?php foreach ($_['possibleOptions'] as $possibleValue => $data): ?>
		<option value="<?php p($possibleValue) ?>" <?php if($data['selected']) echo 'selected="selected"'; ?>>
			<?php p($l->t($data['visibleText'])); ?>
		</option>
		<?php endforeach; ?>
	</select>
	<span class="msg"></span>
	<?php else: ?>
	<p><?php p($l->t('It was not possible to get your session. Please, try reloading the page or logout and login again')); ?></p>
	<?php endif; ?>
</div>
