<?php
/**
 * @author Ilja Neumann <ineumann@owncloud.com>
 *
 * @copyright Copyright (c) 2017, ownCloud GmbH.
 * @license AGPL-3.0
 *
 * This code is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License, version 3,
 * as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License, version 3,
 * along with this program.  If not, see <http://www.gnu.org/licenses/>
 *
 */
namespace OC\Files\Storage\Wrapper;

use OC\Files\Stream\Checksum as ChecksumStream;

class Checksum extends Wrapper {

	/**
	 * @param array $parameters
	 */
	public function __construct($parameters) {
		parent::__construct($parameters);
	}

	/**
	 * @param string $path
	 * @param string $mode
	 * @return false|resource
	 */
	public function fopen($path, $mode) {
		$stream = $this->getWrapperStorage()->fopen($path, $mode);
		if (!self::requiresChecksum($path)) {
			return $stream;
		}

		return \OC\Files\Stream\Checksum::wrap($stream, $path);
	}


	/**
	 * Checksum is only required for everything under files/
	 * @param $path
	 * @return bool
	 */
	private static function requiresChecksum($path) {
		return substr($path, 0, 6) === 'files/';
	}

	/**
	 * @param string $path1
	 * @param string $path2
	 * @return bool
	 */
	public function rename($path1, $path2) {
		$renameOk = $this->getWrapperStorage()->rename($path1, $path2);
		$meta = $this->getMetaData($path1);

		if (isset($meta['checksum'])) {
			$this->getCache()->put(
				$path2,
				["checksum" => $meta['checksum']]
			);
		}

		return $renameOk;
	}

	/**
	 * @param string $path
	 * @param string $data
	 * @return bool
	 */
	public function file_put_contents($path, $data) {
		return parent::file_put_contents($path, $data); // TODO: Change the autogenerated stub
	}

	/**
	 * @param string $path
	 * @return array
	 */
	public function getMetaData($path) {
		$parentMetaData = parent::getMetaData($path);
		$checksums = ChecksumStream::getChecksums();

		if (isset($checksums['path'])) {
			$parentMetaData['checksum'] = $checksums[$path];
		}

		return $parentMetaData;
	}
}