<?php
/**
 * Created by PhpStorm.
 * User: ilja
 * Date: 07.03.17
 * Time: 14:50
 */

namespace OC\Files\Storage\Wrapper;

use OCP\Constants;

class ReadOnlyJail extends DirMask {

	protected function checkPath($path) {
		if ($path === 'files') {
			return true;
		}

		return parent::checkPath($path);
	}

	public function mkdir($path) {

		if ($path === 'files') {
			$this->mask = Constants::PERMISSION_CREATE;
		};

		$result = parent::mkdir($path); // TODO: Change the autogenerated stub

		$this->mask = Constants::PERMISSION_READ;

		return $result;
	}

}