<?php
/**
 * ownCloud
 *
 * @author Phillip Davis <phil@jankaritech.com>
 * @copyright Copyright (c) 2026, ownCloud GmbH
 *
 * This code is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License,
 * as published by the Free Software Foundation;
 * either version 3 of the License, or any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>
 *
 */

use Behat\Config\Config;
use Behat\Config\Extension;
use Behat\Config\Profile;
use Behat\Config\Suite;
use Cjm\Behat\StepThroughExtension\ServiceContainer\StepThroughExtension;
use rdx\behatvars\BehatVariablesExtension;

$suiteSettings = [
	'context' => [
		'parameters' => [
			'ldapAdminPassword' => 'admin',
			'ldapUsersOU' => 'TestUsers',
			'ldapGroupsOU' => 'TestGroups',
			'ldapInitialUserFilePath' => '/../../config/ldap-users.ldif',
		],
	],
];

$featureContextArgs = [
	'baseUrl' => 'http://localhost:8080',
	'adminUsername' => 'admin',
	'adminPassword' => 'admin',
	'regularUserPassword' => 123456,
	'ocPath' => 'apps/testing/api/v1/occ',
];

return (new Config())
	->withProfile(
		(new Profile(
			'default',
			[
			'autoload' => [
			'' => '%paths.base%/../features/bootstrap',
			],
			]
		))
			->withExtension(new Extension(BehatVariablesExtension::class))
			->withExtension(new Extension(StepThroughExtension::class))
			->withSuite(
				(new Suite(
					'apiMain',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('AppManagementContext')
					->addContext('AppConfigurationContext')
					->addContext('CalDavContext')
					->addContext('CardDavContext')
					->addContext('ChecksumContext')
					->addContext('FilesVersionsContext')
					->addContext('OccContext')
					->addContext('TransferOwnershipContext')
					->addContext('TrashbinContext')
					->withPaths('%paths.base%/../features/apiMain')
			)
			->withSuite(
				(new Suite(
					'apiAuth',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('CorsContext')
					->addContext('AuthContext')
					->withPaths('%paths.base%/../features/apiAuth')
			)
			->withSuite(
				(new Suite(
					'apiAuthOcs',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('AuthContext')
					->withPaths('%paths.base%/../features/apiAuthOcs')
			)
			->withSuite(
				(new Suite(
					'apiAuthWebDav',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('LoggingContext')
					->addContext('OccContext')
					->addContext('SearchContext')
					->addContext('PublicWebDavContext')
					->addContext('WebDavPropertiesContext')
					->addContext('AuthContext')
					->withPaths('%paths.base%/../features/apiAuthWebDav')
			)
			->withSuite(
				(new Suite(
					'apiCapabilities',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('CapabilitiesContext')
					->addContext('OccContext')
					->addContext('AppConfigurationContext')
					->withPaths('%paths.base%/../features/apiCapabilities')
			)
			->withSuite(
				(new Suite(
					'apiComments',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('CommentsContext')
					->addContext('WebDavPropertiesContext')
					->withPaths('%paths.base%/../features/apiComments')
			)
			->withSuite(
				(new Suite(
					'apiFavorites',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('FavoritesContext')
					->addContext('WebDavPropertiesContext')
					->addContext('AppConfigurationContext')
					->addContext('OccContext')
					->withPaths('%paths.base%/../features/apiFavorites')
			)
			->withSuite(
				(new Suite(
					'apiFederationToRoot1',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('FederationContext')
					->addContext('WebDavPropertiesContext')
					->addContext('AppConfigurationContext')
					->withPaths('%paths.base%/../features/apiFederationToRoot1')
			)
			->withSuite(
				(new Suite(
					'apiFederationToRoot2',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('FederationContext')
					->addContext('WebDavPropertiesContext')
					->addContext('AppConfigurationContext')
					->withPaths('%paths.base%/../features/apiFederationToRoot2')
			)
			->withSuite(
				(new Suite(
					'apiFederationToShares1',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('FederationContext')
					->addContext('WebDavPropertiesContext')
					->addContext('AppConfigurationContext')
					->addContext('OccContext')
					->withPaths('%paths.base%/../features/apiFederationToShares1')
			)
			->withSuite(
				(new Suite(
					'apiFederationToShares2',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('FederationContext')
					->addContext('WebDavPropertiesContext')
					->addContext('AppConfigurationContext')
					->addContext('OccContext')
					->withPaths('%paths.base%/../features/apiFederationToShares2')
			)
			->withSuite(
				(new Suite(
					'apiProvisioning-v1',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('OccContext')
					->addContext('OccUsersGroupsContext')
					->addContext('AuthContext')
					->addContext('PublicWebDavContext')
					->withPaths('%paths.base%/../features/apiProvisioning-v1')
			)
			->withSuite(
				(new Suite(
					'apiProvisioning-v2',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('OccContext')
					->addContext('OccUsersGroupsContext')
					->addContext('AuthContext')
					->addContext('PublicWebDavContext')
					->withPaths('%paths.base%/../features/apiProvisioning-v2')
			)
			->withSuite(
				(new Suite(
					'apiProvisioningGroups-v1',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('OccContext')
					->addContext('OccUsersGroupsContext')
					->withPaths('%paths.base%/../features/apiProvisioningGroups-v1')
			)
			->withSuite(
				(new Suite(
					'apiProvisioningGroups-v2',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('OccContext')
					->addContext('OccUsersGroupsContext')
					->withPaths('%paths.base%/../features/apiProvisioningGroups-v2')
			)
			->withSuite(
				(new Suite(
					'apiShareCreateSpecialToRoot1',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('OccContext')
					->addContext('TrashbinContext')
					->addContext('WebDavPropertiesContext')
					->addContext('AppConfigurationContext')
					->withPaths('%paths.base%/../features/apiShareCreateSpecialToRoot1')
			)
			->withSuite(
				(new Suite(
					'apiShareCreateSpecialToShares1',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('OccContext')
					->addContext('TrashbinContext')
					->addContext('WebDavPropertiesContext')
					->addContext('AppConfigurationContext')
					->withPaths('%paths.base%/../features/apiShareCreateSpecialToShares1')
			)
			->withSuite(
				(new Suite(
					'apiShareCreateSpecialToRoot2',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('OccContext')
					->addContext('TrashbinContext')
					->addContext('WebDavPropertiesContext')
					->addContext('AppConfigurationContext')
					->withPaths('%paths.base%/../features/apiShareCreateSpecialToRoot2')
			)
			->withSuite(
				(new Suite(
					'apiShareCreateSpecialToShares2',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('OccContext')
					->addContext('TrashbinContext')
					->addContext('WebDavPropertiesContext')
					->addContext('AppConfigurationContext')
					->withPaths('%paths.base%/../features/apiShareCreateSpecialToShares2')
			)
			->withSuite(
				(new Suite(
					'apiSharees',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('ShareesContext')
					->addContext('OccContext')
					->addContext('AppConfigurationContext')
					->withPaths('%paths.base%/../features/apiSharees')
			)
			->withSuite(
				(new Suite(
					'apiShareManagementToRoot',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('OccContext')
					->addContext('PublicWebDavContext')
					->addContext('TrashbinContext')
					->addContext('WebDavPropertiesContext')
					->addContext('AppConfigurationContext')
					->addContext('FilesVersionsContext')
					->withPaths('%paths.base%/../features/apiShareManagementToRoot')
			)
			->withSuite(
				(new Suite(
					'apiShareManagementToShares',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('OccContext')
					->addContext('PublicWebDavContext')
					->addContext('TrashbinContext')
					->addContext('WebDavPropertiesContext')
					->addContext('AppConfigurationContext')
					->addContext('FilesVersionsContext')
					->withPaths('%paths.base%/../features/apiShareManagementToShares')
			)
			->withSuite(
				(new Suite(
					'apiShareManagementBasicToRoot',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('OccContext')
					->addContext('PublicWebDavContext')
					->addContext('TrashbinContext')
					->addContext('WebDavPropertiesContext')
					->addContext('AuthContext')
					->withPaths('%paths.base%/../features/apiShareManagementBasicToRoot')
			)
			->withSuite(
				(new Suite(
					'apiShareManagementBasicToShares',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('OccContext')
					->addContext('PublicWebDavContext')
					->addContext('TrashbinContext')
					->addContext('WebDavPropertiesContext')
					->addContext('AuthContext')
					->withPaths('%paths.base%/../features/apiShareManagementBasicToShares')
			)
			->withSuite(
				(new Suite(
					'apiShareOperationsToRoot1',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('OccContext')
					->addContext('PublicWebDavContext')
					->addContext('TrashbinContext')
					->addContext('WebDavPropertiesContext')
					->withPaths('%paths.base%/../features/apiShareOperationsToRoot1')
			)
			->withSuite(
				(new Suite(
					'apiShareOperationsToRoot2',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('OccContext')
					->addContext('PublicWebDavContext')
					->addContext('TrashbinContext')
					->addContext('WebDavPropertiesContext')
					->withPaths('%paths.base%/../features/apiShareOperationsToRoot2')
			)
			->withSuite(
				(new Suite(
					'apiShareOperationsToShares1',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('OccContext')
					->addContext('PublicWebDavContext')
					->addContext('TrashbinContext')
					->addContext('WebDavPropertiesContext')
					->withPaths('%paths.base%/../features/apiShareOperationsToShares1')
			)
			->withSuite(
				(new Suite(
					'apiShareOperationsToShares2',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('OccContext')
					->addContext('PublicWebDavContext')
					->addContext('TrashbinContext')
					->addContext('WebDavPropertiesContext')
					->withPaths('%paths.base%/../features/apiShareOperationsToShares2')
			)
			->withSuite(
				(new Suite(
					'apiSharePublicLink1',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('OccContext')
					->addContext('PublicWebDavContext')
					->addContext('TrashbinContext')
					->addContext('WebDavPropertiesContext')
					->addContext('AppConfigurationContext')
					->withPaths('%paths.base%/../features/apiSharePublicLink1')
			)
			->withSuite(
				(new Suite(
					'apiSharePublicLink2',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('OccContext')
					->addContext('PublicWebDavContext')
					->addContext('TrashbinContext')
					->addContext('WebDavPropertiesContext')
					->addContext('AppConfigurationContext')
					->withPaths('%paths.base%/../features/apiSharePublicLink2')
			)
			->withSuite(
				(new Suite(
					'apiSharePublicLink3',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('OccContext')
					->addContext('PublicWebDavContext')
					->addContext('TrashbinContext')
					->addContext('WebDavPropertiesContext')
					->addContext('AppConfigurationContext')
					->withPaths('%paths.base%/../features/apiSharePublicLink3')
			)
			->withSuite(
				(new Suite(
					'apiShareReshareToRoot1',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('OccContext')
					->addContext('PublicWebDavContext')
					->addContext('TrashbinContext')
					->addContext('WebDavPropertiesContext')
					->withPaths('%paths.base%/../features/apiShareReshareToRoot1')
			)
			->withSuite(
				(new Suite(
					'apiShareReshareToShares1',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('OccContext')
					->addContext('PublicWebDavContext')
					->addContext('TrashbinContext')
					->addContext('WebDavPropertiesContext')
					->withPaths('%paths.base%/../features/apiShareReshareToShares1')
			)
			->withSuite(
				(new Suite(
					'apiShareReshareToRoot2',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('OccContext')
					->addContext('PublicWebDavContext')
					->addContext('TrashbinContext')
					->addContext('WebDavPropertiesContext')
					->addContext('AppConfigurationContext')
					->withPaths('%paths.base%/../features/apiShareReshareToRoot2')
			)
			->withSuite(
				(new Suite(
					'apiShareReshareToShares2',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('OccContext')
					->addContext('PublicWebDavContext')
					->addContext('TrashbinContext')
					->addContext('WebDavPropertiesContext')
					->addContext('AppConfigurationContext')
					->withPaths('%paths.base%/../features/apiShareReshareToShares2')
			)
			->withSuite(
				(new Suite(
					'apiShareReshareToRoot3',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('OccContext')
					->addContext('PublicWebDavContext')
					->addContext('TrashbinContext')
					->addContext('WebDavPropertiesContext')
					->addContext('AppConfigurationContext')
					->withPaths('%paths.base%/../features/apiShareReshareToRoot3')
			)
			->withSuite(
				(new Suite(
					'apiShareReshareToShares3',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('OccContext')
					->addContext('PublicWebDavContext')
					->addContext('TrashbinContext')
					->addContext('WebDavPropertiesContext')
					->addContext('AppConfigurationContext')
					->withPaths('%paths.base%/../features/apiShareReshareToShares3')
			)
			->withSuite(
				(new Suite(
					'apiShareUpdateToRoot',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('OccContext')
					->addContext('PublicWebDavContext')
					->addContext('TrashbinContext')
					->addContext('WebDavPropertiesContext')
					->addContext('AppConfigurationContext')
					->withPaths('%paths.base%/../features/apiShareUpdateToRoot')
			)
			->withSuite(
				(new Suite(
					'apiShareUpdateToShares',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('OccContext')
					->addContext('PublicWebDavContext')
					->addContext('TrashbinContext')
					->addContext('WebDavPropertiesContext')
					->addContext('AppConfigurationContext')
					->withPaths('%paths.base%/../features/apiShareUpdateToShares')
			)
			->withSuite(
				(new Suite(
					'apiSharingNotificationsToRoot',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('NotificationsCoreContext')
					->addContext('AppConfigurationContext')
					->withPaths('%paths.base%/../features/apiSharingNotificationsToRoot')
			)
			->withSuite(
				(new Suite(
					'apiSharingNotificationsToShares',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('NotificationsCoreContext')
					->addContext('AppConfigurationContext')
					->addContext('OccContext')
					->withPaths('%paths.base%/../features/apiSharingNotificationsToShares')
			)
			->withSuite(
				(new Suite(
					'apiTags',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('TagsContext')
					->addContext('WebDavPropertiesContext')
					->withPaths('%paths.base%/../features/apiTags')
			)
			->withSuite(
				(new Suite(
					'apiTrashbin',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('OccContext')
					->addContext('TrashbinContext')
					->addContext('AppConfigurationContext')
					->addContext('WebDavPropertiesContext')
					->withPaths('%paths.base%/../features/apiTrashbin')
			)
			->withSuite(
				(new Suite(
					'apiTrashbinRestore',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('OccContext')
					->addContext('TrashbinContext')
					->addContext('AppConfigurationContext')
					->addContext('WebDavPropertiesContext')
					->withPaths('%paths.base%/../features/apiTrashbinRestore')
			)
			->withSuite(
				(new Suite(
					'apiVersions',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('ChecksumContext')
					->addContext('FilesVersionsContext')
					->addContext('WebDavPropertiesContext')
					->addContext('OccContext')
					->addContext('AppConfigurationContext')
					->addContext('TrashbinContext')
					->withPaths('%paths.base%/../features/apiVersions')
			)
			->withSuite(
				(new Suite(
					'apiWebdavDelete',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('LoggingContext')
					->addContext('OccContext')
					->addContext('SearchContext')
					->addContext('PublicWebDavContext')
					->addContext('WebDavPropertiesContext')
					->addContext('TagsContext')
					->addContext('TrashbinContext')
					->withPaths('%paths.base%/../features/apiWebdavDelete')
			)
			->withSuite(
				(new Suite(
					'apiWebdavLocks',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('OccContext')
					->addContext('PublicWebDavContext')
					->addContext('WebDavLockingContext')
					->addContext('WebDavPropertiesContext')
					->withPaths('%paths.base%/../features/apiWebdavLocks')
			)
			->withSuite(
				(new Suite(
					'apiWebdavLocks2',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('OccContext')
					->addContext('PublicWebDavContext')
					->addContext('WebDavLockingContext')
					->addContext('WebDavPropertiesContext')
					->withPaths('%paths.base%/../features/apiWebdavLocks2')
			)
			->withSuite(
				(new Suite(
					'apiWebdavLocks3',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('OccContext')
					->addContext('PublicWebDavContext')
					->addContext('WebDavLockingContext')
					->addContext('WebDavPropertiesContext')
					->withPaths('%paths.base%/../features/apiWebdavLocks3')
			)
			->withSuite(
				(new Suite(
					'apiWebdavLocksUnlock',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('OccContext')
					->addContext('PublicWebDavContext')
					->addContext('WebDavLockingContext')
					->addContext('WebDavPropertiesContext')
					->withPaths('%paths.base%/../features/apiWebdavLocksUnlock')
			)
			->withSuite(
				(new Suite(
					'apiWebdavMove1',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('LoggingContext')
					->addContext('OccContext')
					->addContext('WebDavPropertiesContext')
					->withPaths('%paths.base%/../features/apiWebdavMove1')
			)
			->withSuite(
				(new Suite(
					'apiWebdavMove2',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('LoggingContext')
					->addContext('OccContext')
					->addContext('WebDavPropertiesContext')
					->withPaths('%paths.base%/../features/apiWebdavMove2')
			)
			->withSuite(
				(new Suite(
					'apiWebdavOperations',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('LoggingContext')
					->addContext('OccContext')
					->addContext('SearchContext')
					->addContext('PublicWebDavContext')
					->addContext('WebDavPropertiesContext')
					->addContext('TagsContext')
					->addContext('TrashbinContext')
					->withPaths('%paths.base%/../features/apiWebdavOperations')
			)
			->withSuite(
				(new Suite(
					'apiWebdavPreviews',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('WebDavPropertiesContext')
					->addContext('OccContext')
					->withPaths('%paths.base%/../features/apiWebdavPreviews')
			)
			->withSuite(
				(new Suite(
					'apiWebdavProperties1',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('LoggingContext')
					->addContext('OccContext')
					->addContext('WebDavPropertiesContext')
					->addContext('AppConfigurationContext')
					->withPaths('%paths.base%/../features/apiWebdavProperties1')
			)
			->withSuite(
				(new Suite(
					'apiWebdavProperties2',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('LoggingContext')
					->addContext('WebDavPropertiesContext')
					->addContext('AppConfigurationContext')
					->withPaths('%paths.base%/../features/apiWebdavProperties2')
			)
			->withSuite(
				(new Suite(
					'apiWebdavUpload1',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('LoggingContext')
					->addContext('OccContext')
					->addContext('PublicWebDavContext')
					->addContext('WebDavPropertiesContext')
					->withPaths('%paths.base%/../features/apiWebdavUpload1')
			)
			->withSuite(
				(new Suite(
					'apiWebdavUpload2',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('LoggingContext')
					->addContext('OccContext')
					->addContext('PublicWebDavContext')
					->withPaths('%paths.base%/../features/apiWebdavUpload2')
			)
			->withSuite(
				(new Suite(
					'apiWebdavEtagPropagation1',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('LoggingContext')
					->addContext('OccContext')
					->addContext('TrashbinContext')
					->addContext('PublicWebDavContext')
					->addContext('FilesVersionsContext')
					->addContext('WebDavPropertiesContext')
					->addContext('AppConfigurationContext')
					->withPaths('%paths.base%/../features/apiWebdavEtagPropagation1')
			)
			->withSuite(
				(new Suite(
					'apiWebdavEtagPropagation2',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('LoggingContext')
					->addContext('OccContext')
					->addContext('TrashbinContext')
					->addContext('PublicWebDavContext')
					->addContext('FilesVersionsContext')
					->addContext('WebDavPropertiesContext')
					->addContext('AppConfigurationContext')
					->withPaths('%paths.base%/../features/apiWebdavEtagPropagation2')
			)
			->withSuite(
				(new Suite(
					'apiTranslation',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->withPaths('%paths.base%/../features/apiTranslation')
			)
			->withSuite(
				(new Suite(
					'cliBackground',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('OccContext')
					->addContext('LoggingContext')
					->withPaths('%paths.base%/../features/cliBackground')
			)
			->withSuite(
				(new Suite(
					'cliCreateLocalStorage',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('OccContext')
					->addContext('AuthContext')
					->withPaths('%paths.base%/../features/cliCreateLocalStorage')
			)
			->withSuite(
				(new Suite(
					'cliDbConversion',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('OccContext')
					->withPaths('%paths.base%/../features/cliDbConversion')
			)
			->withSuite(
				(new Suite(
					'cliEncryption',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('OccContext')
					->addContext('WebDavPropertiesContext')
					->addContext('EncryptionContext')
					->withPaths('%paths.base%/../features/cliEncryption')
			)
			->withSuite(
				(new Suite(
					'cliExternalStorage',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('FederationContext')
					->addContext('OccContext')
					->addContext('WebDavPropertiesContext')
					->addContext('PublicWebDavContext')
					->withPaths('%paths.base%/../features/cliExternalStorage')
			)
			->withSuite(
				(new Suite(
					'cliLocalStorage',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('OccContext')
					->addContext('AuthContext')
					->withPaths('%paths.base%/../features/cliLocalStorage')
			)
			->withSuite(
				(new Suite(
					'cliMain',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('OccContext')
					->addContext('CapabilitiesContext')
					->addContext('CalDavContext')
					->addContext('CardDavContext')
					->addContext('TransferOwnershipContext')
					->addContext('FederationContext')
					->addContext('WebDavPropertiesContext')
					->addContext('FilesVersionsContext')
					->addContext('PublicWebDavContext')
					->addContext('AppConfigurationContext')
					->withPaths('%paths.base%/../features/cliMain')
			)
			->withSuite(
				(new Suite(
					'cliManageApps',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('OccContext')
					->addContext('AppManagementContext')
					->withPaths('%paths.base%/../features/cliManageApps')
			)
			->withSuite(
				(new Suite(
					'cliProvisioning',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('EmailContext')
					->addContext('OccContext')
					->addContext('OccAppManagementContext')
					->addContext('OccUsersGroupsContext')
					->withPaths('%paths.base%/../features/cliProvisioning')
			)
			->withSuite(
				(new Suite(
					'cliTrashbin',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('OccContext')
					->addContext('TrashbinContext')
					->withPaths('%paths.base%/../features/cliTrashbin')
			)
			->withSuite(
				(new Suite(
					'webUIAdminSettings',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('EmailContext')
					->addContext('CapabilitiesContext')
					->addContext('WebUIAdminAppsSettingsContext')
					->addContext('WebUIAdminSharingSettingsContext')
					->addContext('WebUIAdminGeneralSettingsContext')
					->addContext('WebUIAdminStorageSettingsContext')
					->addContext('WebUIFilesContext')
					->addContext('WebUIHelpAndTipsContext')
					->addContext('WebUIGeneralContext')
					->addContext('WebUILoginContext')
					->addContext('WebUISharingContext')
					->addContext('OccContext')
					->withPaths('%paths.base%/../features/webUIAdminSettings')
			)
			->withSuite(
				(new Suite(
					'webUIComments',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('WebUIGeneralContext')
					->addContext('WebUILoginContext')
					->addContext('WebUIFilesContext')
					->addContext('WebUISharingContext')
					->withPaths('%paths.base%/../features/webUIComments')
			)
			->withSuite(
				(new Suite(
					'webUICreateDelete',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('OccContext')
					->addContext('TagsContext')
					->addContext('WebUIFilesContext')
					->addContext('WebUIGeneralContext')
					->addContext('WebUILoginContext')
					->addContext('WebUISharingContext')
					->addContext('WebUINewFileMenuContext')
					->withPaths('%paths.base%/../features/webUICreateDelete')
			)
			->withSuite(
				(new Suite(
					'webUIFavorites',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('WebUIFilesContext')
					->addContext('WebUIGeneralContext')
					->addContext('WebUILoginContext')
					->withPaths('%paths.base%/../features/webUIFavorites')
			)
			->withSuite(
				(new Suite(
					'webUIFiles',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('TagsContext')
					->addContext('WebUIFilesContext')
					->addContext('WebUIGeneralContext')
					->addContext('WebUILoginContext')
					->addContext('WebUISearchContext')
					->addContext('WebUISharingContext')
					->addContext('OccContext')
					->addContext('PublicWebDavContext')
					->withPaths('%paths.base%/../features/webUIFiles')
			)
			->withSuite(
				(new Suite(
					'webUILogin',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('EmailContext')
					->addContext('OccContext')
					->addContext('WebUIFilesContext')
					->addContext('WebUIGeneralContext')
					->addContext('WebUILoginContext')
					->addContext('WebUIPersonalGeneralSettingsContext')
					->withPaths('%paths.base%/../features/webUILogin')
			)
			->withSuite(
				(new Suite(
					'webUIMoveFilesFolders',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('WebUIFilesContext')
					->addContext('WebUIGeneralContext')
					->addContext('WebUILoginContext')
					->addContext('WebUISharingContext')
					->addContext('OccContext')
					->addContext('PublicWebDavContext')
					->withPaths('%paths.base%/../features/webUIMoveFilesFolders')
			)
			->withSuite(
				(new Suite(
					'webUIPersonalSettings',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('EmailContext')
					->addContext('WebUIFilesContext')
					->addContext('WebUIGeneralContext')
					->addContext('WebUILoginContext')
					->addContext('WebUIPersonalGeneralSettingsContext')
					->addContext('WebUIPersonalSecuritySettingsContext')
					->addContext('WebUIUserContext')
					->addContext('OccContext')
					->addContext('OccUsersGroupsContext')
					->withPaths('%paths.base%/../features/webUIPersonalSettings')
			)
			->withSuite(
				(new Suite(
					'webUIRenameFiles',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('WebUIFilesContext')
					->addContext('WebUIGeneralContext')
					->addContext('WebUILoginContext')
					->addContext('WebUISharingContext')
					->addContext('OccContext')
					->addContext('PublicWebDavContext')
					->withPaths('%paths.base%/../features/webUIRenameFiles')
			)
			->withSuite(
				(new Suite(
					'webUIRenameFolders',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('WebUIFilesContext')
					->addContext('WebUIGeneralContext')
					->addContext('WebUILoginContext')
					->addContext('OccContext')
					->withPaths('%paths.base%/../features/webUIRenameFolders')
			)
			->withSuite(
				(new Suite(
					'webUIRestrictSharing',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('WebUIFilesContext')
					->addContext('WebUIGeneralContext')
					->addContext('WebUILoginContext')
					->addContext('WebUISharingContext')
					->withPaths('%paths.base%/../features/webUIRestrictSharing')
			)
			->withSuite(
				(new Suite(
					'webUISharingAcceptShares',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('OccContext')
					->addContext('WebUIFilesContext')
					->addContext('WebUIGeneralContext')
					->addContext('WebUILoginContext')
					->addContext('WebUISharingContext')
					->addContext('WebUIAdminSharingSettingsContext')
					->addContext('WebUIPersonalSharingSettingsContext')
					->withPaths('%paths.base%/../features/webUISharingAcceptShares')
			)
			->withSuite(
				(new Suite(
					'webUISharingAutocompletion1',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('AppConfigurationContext')
					->addContext('WebUIFilesContext')
					->addContext('WebUIGeneralContext')
					->addContext('WebUILoginContext')
					->addContext('WebUISharingContext')
					->addContext('OccContext')
					->addContext('WebUIPersonalSharingSettingsContext')
					->withPaths('%paths.base%/../features/webUISharingAutocompletion1')
			)
			->withSuite(
				(new Suite(
					'webUISharingAutocompletion2',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('AppConfigurationContext')
					->addContext('WebUIFilesContext')
					->addContext('WebUIGeneralContext')
					->addContext('WebUILoginContext')
					->addContext('WebUISharingContext')
					->addContext('OccContext')
					->addContext('WebUIPersonalSharingSettingsContext')
					->withPaths('%paths.base%/../features/webUISharingAutocompletion2')
			)
			->withSuite(
				(new Suite(
					'webUISharingExternal1',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('AppConfigurationContext')
					->addContext('EmailContext')
					->addContext('FederationContext')
					->addContext('WebUIFilesContext')
					->addContext('WebUIGeneralContext')
					->addContext('WebUILoginContext')
					->addContext('WebUISharingContext')
					->addContext('OccContext')
					->addContext('PublicWebDavContext')
					->addContext('WebUIPersonalSharingSettingsContext')
					->addContext('WebUIAdminSharingSettingsContext')
					->withPaths('%paths.base%/../features/webUISharingExternal1')
			)
			->withSuite(
				(new Suite(
					'webUISharingExternal2',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('AppConfigurationContext')
					->addContext('EmailContext')
					->addContext('FederationContext')
					->addContext('WebUIFilesContext')
					->addContext('WebUIGeneralContext')
					->addContext('WebUILoginContext')
					->addContext('WebUISharingContext')
					->addContext('OccContext')
					->addContext('PublicWebDavContext')
					->addContext('WebUIPersonalSharingSettingsContext')
					->addContext('WebUIAdminSharingSettingsContext')
					->withPaths('%paths.base%/../features/webUISharingExternal2')
			)
			->withSuite(
				(new Suite(
					'webUISharingInternalGroups1',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('WebUIFilesContext')
					->addContext('WebUIGeneralContext')
					->addContext('WebUILoginContext')
					->addContext('WebUISharingContext')
					->addContext('EmailContext')
					->addContext('WebUIAdminSharingSettingsContext')
					->addContext('OccContext')
					->withPaths('%paths.base%/../features/webUISharingInternalGroups1')
			)
			->withSuite(
				(new Suite(
					'webUISharingInternalGroups2',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('WebUIFilesContext')
					->addContext('WebUIGeneralContext')
					->addContext('WebUILoginContext')
					->addContext('WebUISharingContext')
					->addContext('EmailContext')
					->addContext('WebUIAdminSharingSettingsContext')
					->addContext('OccContext')
					->withPaths('%paths.base%/../features/webUISharingInternalGroups2')
			)
			->withSuite(
				(new Suite(
					'webUISharingInternalUsers1',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('WebUIFilesContext')
					->addContext('WebUIGeneralContext')
					->addContext('WebUILoginContext')
					->addContext('WebUISharingContext')
					->addContext('EmailContext')
					->addContext('WebUIAdminSharingSettingsContext')
					->addContext('WebUIPersonalSharingSettingsContext')
					->addContext('OccContext')
					->withPaths('%paths.base%/../features/webUISharingInternalUsers1')
			)
			->withSuite(
				(new Suite(
					'webUISharingInternalUsers2',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('WebUIFilesContext')
					->addContext('WebUIGeneralContext')
					->addContext('WebUILoginContext')
					->addContext('WebUISharingContext')
					->addContext('EmailContext')
					->addContext('WebUIAdminSharingSettingsContext')
					->addContext('WebUIPersonalSharingSettingsContext')
					->addContext('OccContext')
					->withPaths('%paths.base%/../features/webUISharingInternalUsers2')
			)
			->withSuite(
				(new Suite(
					'webUISharingNotifications',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('NotificationsCoreContext')
					->addContext('WebUIFilesContext')
					->addContext('WebUIGeneralContext')
					->addContext('WebUILoginContext')
					->addContext('WebUINotificationsContext')
					->addContext('WebUISharingContext')
					->withPaths('%paths.base%/../features/webUISharingNotifications')
			)
			->withSuite(
				(new Suite(
					'webUISharingPublic1',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('AppConfigurationContext')
					->addContext('EmailContext')
					->addContext('OccContext')
					->addContext('PublicWebDavContext')
					->addContext('WebUIFilesContext')
					->addContext('WebUIGeneralContext')
					->addContext('WebUILoginContext')
					->addContext('WebUISharingContext')
					->withPaths('%paths.base%/../features/webUISharingPublic1')
			)
			->withSuite(
				(new Suite(
					'webUISharingPublic2',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('AppConfigurationContext')
					->addContext('EmailContext')
					->addContext('OccContext')
					->addContext('PublicWebDavContext')
					->addContext('WebUIFilesContext')
					->addContext('WebUIGeneralContext')
					->addContext('WebUILoginContext')
					->addContext('WebUISharingContext')
					->withPaths('%paths.base%/../features/webUISharingPublic2')
			)
			->withSuite(
				(new Suite(
					'webUITags',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('TagsContext')
					->addContext('WebUIGeneralContext')
					->addContext('WebUILoginContext')
					->addContext('WebUIFilesContext')
					->addContext('WebUISharingContext')
					->addContext('WebUITagsContext')
					->withPaths('%paths.base%/../features/webUITags')
			)
			->withSuite(
				(new Suite(
					'webUITrashbin',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('OccContext')
					->addContext('TrashbinContext')
					->addContext('WebUIFilesContext')
					->addContext('WebUIGeneralContext')
					->addContext('WebUILoginContext')
					->withPaths('%paths.base%/../features/webUITrashbin')
			)
			->withSuite(
				(new Suite(
					'webUIUpload',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('WebUIFilesContext')
					->addContext('WebUIGeneralContext')
					->addContext('WebUILoginContext')
					->addContext('WebUISharingContext')
					->addContext('OccContext')
					->addContext('PublicWebDavContext')
					->withPaths('%paths.base%/../features/webUIUpload')
			)
			->withSuite(
				(new Suite(
					'webUIAddUsers',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('EmailContext')
					->addContext('WebDavPropertiesContext')
					->addContext('WebUIFilesContext')
					->addContext('WebUIGeneralContext')
					->addContext('WebUILoginContext')
					->addContext('WebUIPersonalGeneralSettingsContext')
					->addContext('WebUIUsersContext')
					->addContext('WebUIUserContext')
					->withPaths('%paths.base%/../features/webUIAddUsers')
			)
			->withSuite(
				(new Suite(
					'webUIManageQuota',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('WebDavPropertiesContext')
					->addContext('WebUIFilesContext')
					->addContext('WebUIGeneralContext')
					->addContext('WebUILoginContext')
					->addContext('WebUIUsersContext')
					->withPaths('%paths.base%/../features/webUIManageQuota')
			)
			->withSuite(
				(new Suite(
					'webUIManageUsersGroups',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('EmailContext')
					->addContext('WebDavPropertiesContext')
					->addContext('WebUIFilesContext')
					->addContext('WebUIGeneralContext')
					->addContext('WebUILoginContext')
					->addContext('WebUIPersonalGeneralSettingsContext')
					->addContext('WebUIUsersContext')
					->addContext('WebUIUserContext')
					->withPaths('%paths.base%/../features/webUIManageUsersGroups')
			)
			->withSuite(
				(new Suite(
					'webUISettingsMenu',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('WebDavPropertiesContext')
					->addContext('EmailContext')
					->addContext('WebUIFilesContext')
					->addContext('WebUIGeneralContext')
					->addContext('WebUILoginContext')
					->addContext('WebUISharingContext')
					->addContext('WebUIUsersContext')
					->withPaths('%paths.base%/../features/webUISettingsMenu')
			)
			->withSuite(
				(new Suite(
					'webUIWebdavLocks',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('WebDavLockingContext')
					->addContext('WebUIAdminGeneralSettingsContext')
					->addContext('WebUIFilesContext')
					->addContext('WebUIGeneralContext')
					->addContext('WebUILoginContext')
					->addContext('WebUIWebDavLockingContext')
					->addContext('WebUISharingContext')
					->addContext('OccContext')
					->addContext('PublicWebDavContext')
					->withPaths('%paths.base%/../features/webUIWebdavLocks')
			)
			->withSuite(
				(new Suite(
					'webUIWebdavLockProtection',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('WebDavLockingContext')
					->addContext('WebUIFilesContext')
					->addContext('WebUIGeneralContext')
					->addContext('WebUILoginContext')
					->addContext('WebUIWebDavLockingContext')
					->addContext('WebUISharingContext')
					->addContext('OccContext')
					->addContext('PublicWebDavContext')
					->withPaths('%paths.base%/../features/webUIWebdavLockProtection')
			)
			->withSuite(
				(new Suite(
					'webUIFileActionsMenu',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('WebUIFilesContext')
					->addContext('WebUIGeneralContext')
					->addContext('WebUILoginContext')
					->addContext('WebUIFileActionsMenuContext')
					->withPaths('%paths.base%/../features/webUIFileActionsMenu')
			)
			->withSuite(
				(new Suite(
					'webUIWithCLI',
					$suiteSettings
				))
					->addContext(
						'FeatureContext',
						$featureContextArgs
					)
					->addContext('EmailContext')
					->addContext('WebUIFilesContext')
					->addContext('WebUIGeneralContext')
					->addContext('WebUILoginContext')
					->addContext('WebUIPersonalGeneralSettingsContext')
					->addContext('WebUIPersonalSecuritySettingsContext')
					->addContext('WebUIUserContext')
					->addContext('OccContext')
					->addContext('OccUsersGroupsContext')
					->addContext('CapabilitiesContext')
					->addContext('WebUIAdminAppsSettingsContext')
					->addContext('WebUIAdminSharingSettingsContext')
					->addContext('WebUIAdminGeneralSettingsContext')
					->addContext('WebUIAdminStorageSettingsContext')
					->addContext('WebUIHelpAndTipsContext')
					->addContext('WebUISharingContext')
					->withPaths('%paths.base%/../features/webUIWithCLI')
			)
	);
