<?php
define('DEBUG',true);
$CONFIG = array (
  'instanceid' => 'ocd9b6a106e1',
  'passwordsalt' => '085c4c55230015a8b8928279be3b9e',
  'trusted_domains' =>
  array (
  ),
  'datadirectory' => $OC::SERVERROOT.'data',
  'dbtype' => 'mysql',
  'version' => '7.0.2.1',
  'dbname' => 'oc_owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => OC_Util::decryptText('/O9Zwe9PinPg836es+uqnMLmc7gAVMMrQds6cNvrtzc='),
  'dbpassword' => OC_Util::decryptText('twoWGovuE6BcC6KSFm/T6hwchjEKxtdri8DcEfjkjNW3fWwei6lifGo1hqXC3GuL'),
  'installed' => true,
  'custom_csp_policy' => 'default-src \'self\'; script-src \'self\' \'unsafe-eval\' \'unsafe-inline\'; style-src \'self\' \'unsafe-inline\'; frame-src *; img-src *; font-src \'self\' data:; media-src *',
  'forcessl' => false,
  'knowledgebaseenabled' => false,
  'maxZipInputSize' => 2147483648,
  'theme' => 'NCDrive',
  'maintenance' => false,
  'appstoreenabled' => false,
  'mail_smtpmode' => 'php',
  'mail_smtpname' => 'owncloud',
  'mail_smtppassword' => 'owncloud',
  'ldapIgnoreNamingRules' => false,
  'mail_smtpmode' => 'smtp',
  'mail_smtpname' => 'quisa137@gmail.com',
  'mail_from_address' => 'ncdrive',
  'mail_domain' => 'ncsoft.com',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => true,
  'mail_smtphost' => 'smtp.gmail.com',
  'mail_smtpsecure' => 'tls',
  'mail_smtppassword' => 'dpffmdktkf',
  'mail_smtpport' => '587',
  'customclient_desktop' => '/agent_down.php',
  //'preview_libreoffice_path' => '/usr/bin/libreoffice',
  // 'enable_previews' => true,
  // 'preview_max_x' => 640,
  // 'preview_max_y' => 640,
  // 'preview_max_scale_factor' => 10,

);
