<?php script('notifications_mail', 'notification_options'); ?>
<div id="email_notifications" class="section">
	<h2><?php p($l->t('Notifications Email'));?></h2>
	<p><?php p($l->t('You can receive notifications generated by any app in your configured email address. Choose if you let ownCloud to send you such emails.')); ?></p>
	<select id="email_sending_option">
		<?php foreach ($_['possibleOptions'] as $possibleValue => $data): ?>
		<option value="<?php p($possibleValue) ?>" <?php if($data['selected']) echo 'selected="selected"'; ?>>
			<?php p($l->t($data['visibleText'])); ?>
		</option>
		<?php endforeach; ?>
	</select>
	<span class="msg"></span>
</div>
