name: Changelog

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  changelog:
    uses: owncloud/reusable-workflows/.github/workflows/calens.yml@main
    secrets:
      APP_ID: ${{ secrets.CALENS_APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.CALENS_APP_PRIVATE_KEY }}
