name: CI

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  semantic-git-messages:
    name: Commits
    uses: owncloud/reusable-workflows/.github/workflows/semantic-git-message.yml@main

  js-unit:
    name: JavaScript Unit
    uses: ./.github/workflows/js-unit.yml

  php-unit:
    name: PHP Unit
    uses: ./.github/workflows/php-unit.yml
    with:
      php-versions: '["8.3"]'

  calens:
    name: Changelog lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Validate changelog entries
        uses: actionhippie/calens@6c54a62bb0c9ac28f361e40f536fe0c69ba50e34 # v1.14.1

  acceptance-api-smoke:
    if: ${{ !contains(github.event.pull_request.title, 'full-ci') }}
    name: API Smoke Tests
    needs: [semantic-git-messages]
    uses: ./.github/workflows/acceptance.yml
    with:
      do-api-tests: true
      server-folder: 'server'
      federated-folder: 'federated'
      additional-app: 'notifications'
      additional-packages: 'imagemagick'
      filter-tags: '@smokeTest'
      test-suites: "['apiComments,apiFavorites,apiFederationToRoot1,apiFederationToRoot2,apiMain']"

  acceptance-api:
    if: contains(github.event.pull_request.title, 'full-ci')
    name: API Tests
    needs: [semantic-git-messages, php-unit, calens]
    uses: ./.github/workflows/acceptance.yml
    with:
      do-api-tests: true
      server-folder: 'server'
      test-suites: "[
        'apiAuth,apiAuthOcs,apiAuthWebDav',
        'apiCapabilities,apiComments,apiFavorites,apiMain',
        'apiProvisioning-v1,apiProvisioning-v2',
        'apiProvisioningGroups-v1,apiProvisioningGroups-v2',
        'apiShareCreateSpecialToRoot1,apiShareCreateSpecialToRoot2',
        'apiShareCreateSpecialToShares1,apiShareCreateSpecialToShares2',
        'apiSharees,apiWebdavOperations',
        'apiShareManagementBasicToRoot,apiShareManagementBasicToShares',
        'apiShareManagementToRoot,apiShareManagementToShares',
        'apiShareOperationsToRoot1,apiShareOperationsToRoot2',
        'apiShareOperationsToShares1,apiShareOperationsToShares2',
        'apiSharePublicLink1,apiSharePublicLink2,apiSharePublicLink3',
        'apiShareReshareToRoot1,apiShareReshareToRoot2,apiShareReshareToRoot3',
        'apiShareReshareToShares1,apiShareReshareToShares2,apiShareReshareToShares3',
        'apiShareUpdateToRoot,apiShareUpdateToShares,apiTags,apiTranslation',
        'apiTrashbin,apiTrashbinRestore',
        'apiVersions,apiWebdavDelete',
        'apiWebdavEtagPropagation1,apiWebdavEtagPropagation2',
        'apiWebdavLocks,apiWebdavLocks2',
        'apiWebdavLocks3,apiWebdavLocksUnlock',
        'apiWebdavMove1,apiWebdavMove2',
        'apiWebdavProperties1,apiWebdavProperties2',
        'apiWebdavUpload1,apiWebdavUpload2,apiWebdavUploadTUS']"

  acceptance-api-notifications:
    if: contains(github.event.pull_request.title, 'full-ci')
    name: API Tests Notifications
    needs: [semantic-git-messages, php-unit, calens]
    uses: ./.github/workflows/acceptance.yml
    with:
      do-api-tests: true
      server-folder: 'server'
      additional-app: 'notifications'
      test-suites: "['apiSharingNotificationsToRoot,apiSharingNotificationsToShares']"

  acceptance-api-previews:
    if: contains(github.event.pull_request.title, 'full-ci')
    name: API Tests Previews
    needs: [semantic-git-messages, php-unit, calens]
    uses: ./.github/workflows/acceptance.yml
    with:
      do-api-tests: true
      additional-packages: 'imagemagick'
      server-folder: 'server'
      test-suites: "['apiWebdavPreviews']"

  acceptance-api-federation:
    if: contains(github.event.pull_request.title, 'full-ci')
    name: API Tests Federation
    needs: [semantic-git-messages, php-unit, calens]
    uses: ./.github/workflows/acceptance.yml
    with:
      do-api-tests: true
      server-folder: 'server'
      federated-folder: 'federated'
      test-suites: "['apiFederationToRoot1,apiFederationToRoot2', 'apiFederationToShares1,apiFederationToShares2']"

  acceptance-cli-smoke:
    if: ${{ !contains(github.event.pull_request.title, 'full-ci') }}
    name: CLI Smoke Tests
    needs: [semantic-git-messages, php-unit, calens]
    uses: ./.github/workflows/acceptance.yml
    with:
      do-cli-tests: true
      use-email-server: true
      server-folder: 'server'
      filter-tags: '@smokeTest'

  acceptance-cli:
    if: contains(github.event.pull_request.title, 'full-ci')
    name: CLI Tests
    needs: [semantic-git-messages, php-unit, calens]
    uses: ./.github/workflows/acceptance.yml
    with:
      do-cli-tests: true
      server-folder: 'server'
      test-suites: "['cliBackground,cliMain,cliManageApps,cliTrashbin']"

  acceptance-cli-email:
    if: contains(github.event.pull_request.title, 'full-ci')
    name: CLI Tests with Email
    needs: [semantic-git-messages, php-unit, calens]
    uses: ./.github/workflows/acceptance.yml
    with:
      do-cli-tests: true
      use-email-server: true
      server-folder: 'server'
      test-suites: "['cliProvisioning']"
