name: CI

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  semantic-git-messages:
    name: Commits
    uses: owncloud/reusable-workflows/.github/workflows/semantic-git-message.yml@main

  php-unit:
    name: PHP Unit
    uses: ./.github/workflows/php-unit.yml
    with:
      php-versions: '["8.3"]'

  calens:
    name: Changelog lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Validate changelog entries
        uses: actionhippie/calens@0b8ceba55a72f5ef8b7d910698fcd28be8bb8c19 # v1.13.4

  acceptance-api:
    name: API Tests
    uses: ./.github/workflows/acceptance.yml
    with:
      do-api-tests: true
      server-folder: 'server'
      test-suites: "[
        'apiAuth',
        'apiAuthOcs',
        'apiAuthWebDav',
        'apiCapabilities',
        'apiComments',
        'apiFavorites',
        'apiMain',
        'apiProvisioning-v1',
        'apiProvisioning-v2',
        'apiProvisioningGroups-v1',
        'apiProvisioningGroups-v2',
        'apiShareCreateSpecialToRoot1',
        'apiShareCreateSpecialToRoot2',
        'apiShareCreateSpecialToShares1',
        'apiShareCreateSpecialToShares2',
        'apiSharees',
        'apiShareManagementBasicToRoot',
        'apiShareManagementBasicToShares',
        'apiShareManagementToRoot',
        'apiShareManagementToShares',
        'apiShareOperationsToRoot1',
        'apiShareOperationsToRoot2',
        'apiShareOperationsToShares1',
        'apiShareOperationsToShares2',
        'apiSharePublicLink1',
        'apiSharePublicLink2',
        'apiSharePublicLink3',
        'apiShareReshareToRoot1',
        'apiShareReshareToRoot2',
        'apiShareReshareToRoot3',
        'apiShareReshareToShares1',
        'apiShareReshareToShares2',
        'apiShareReshareToShares3',
        'apiShareUpdateToRoot',
        'apiShareUpdateToShares',
        'apiTags',
        'apiTranslation',
        'apiTrashbin',
        'apiTrashbinRestore',
        'apiVersions',
        'apiWebdavDelete',
        'apiWebdavEtagPropagation1',
        'apiWebdavEtagPropagation2',
        'apiWebdavLocks',
        'apiWebdavLocks2',
        'apiWebdavLocks3',
        'apiWebdavLocksUnlock',
        'apiWebdavMove1',
        'apiWebdavMove2',
        'apiWebdavOperations',
        'apiWebdavProperties1',
        'apiWebdavProperties2',
        'apiWebdavUpload1',
        'apiWebdavUpload2',
        'apiWebdavUploadTUS']"

  acceptance-api-notifications:
    name: API Tests Notifications
    uses: ./.github/workflows/acceptance.yml
    with:
      do-api-tests: true
      server-folder: 'server'
      additional-app: 'notifications'
      test-suites: "['apiSharingNotificationsToRoot', 'apiSharingNotificationsToShares']"

  acceptance-api-previews:
    name: API Tests Previews
    uses: ./.github/workflows/acceptance.yml
    with:
      do-api-tests: true
      additional-packages: 'imagemagick'
      server-folder: 'server'
      test-suites: "['apiWebdavPreviews']"

  acceptance-api-federation:
    name: API Tests Federation
    uses: ./.github/workflows/acceptance.yml
    with:
      do-api-tests: true
      server-folder: 'server'
      federated-folder: 'federated'
      test-suites: "['apiFederationToRoot1', 'apiFederationToRoot2', 'apiFederationToShares1', 'apiFederationToShares2']"

  acceptance-cli:
    name: CLI Tests
    uses: ./.github/workflows/acceptance.yml
    with:
      do-cli-tests: true
      server-folder: 'server'
      test-suites: "['cliMain', 'cliTrashbin']"

  acceptance-cli-email:
    name: CLI Tests
    uses: ./.github/workflows/acceptance.yml
    with:
      do-cli-tests: true
      use-email-server: true
      server-folder: 'server'
      test-suites: "['cliProvisioning']"
