name: Lint and Code Style

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
    contents: read

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-php-codestyle:
    name: PHP Code Style
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ["8.3"]
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup PHP
        uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # v2.37.1
        with:
          php-version: ${{ matrix.php-version }}
          extensions: curl, gd, json, xml, zip
          ini-values: "memory_limit=1024M"
          tools: phpstan, codesniffer

      - name: Install Composer dependencies
        run: |
          make install-composer-deps
          make vendor-bin-deps

      - name: Install Server
        run: |
          DATA_DIRECTORY=$(pwd)/data bash tests/drone/install-server.sh

      - name: Run PHP Code Style Checks
        run: |
          make test-php-style

      - name: Run PHP Stan
        run: |
          make test-php-phpstan

      - name: Run PHP Phan
        run: |
          make test-php-phan
